name: refund_checker
description: Refund Status Checker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  file_picker: ^8.1.2
  excel: 4.0.3
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  wakelock_plus: 1.2.8
  android_id: ^0.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"

dependency_overrides:
  archive: ^3.6.1
  package_info_plus: 8.0.2
